//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudoArchictetureDDDVS2015Util.Mensagens {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensGenericas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensGenericas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EstudoArchictetureDDDVS2015Util.Mensagens.MensagensGenericas", typeof(MensagensGenericas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A Action ~/{0}/{1} precisa de parametros.
        /// </summary>
        public static string AActionPrecisaDeParametros {
            get {
                return ResourceManager.GetString("AActionPrecisaDeParametros", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ação realizada com sucesso.
        /// </summary>
        public static string AcaoRealizadaComSucesso {
            get {
                return ResourceManager.GetString("AcaoRealizadaComSucesso", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A action EditarSinistro na controller AvisoSinistro não conseguiu recuperar informações de forma de financiamento.
        /// </summary>
        public static string ActionNaoRecuperouFormaFinancimento {
            get {
                return ResourceManager.GetString("ActionNaoRecuperouFormaFinancimento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A informação &apos;{0}&apos; na coluna {1} está em um formato inválido..
        /// </summary>
        public static string AInformacaoNaColunaEstaEmFormatoInvalido {
            get {
                return ResourceManager.GetString("AInformacaoNaColunaEstaEmFormatoInvalido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O arquivo não está no formato correto. É necessário escolher um arquivo em formato &apos;Texto em Unicode&apos;..
        /// </summary>
        public static string ArquivoNaoEstaEmFormatoCorretoFormatoTextoEmUnicode {
            get {
                return ResourceManager.GetString("ArquivoNaoEstaEmFormatoCorretoFormatoTextoEmUnicode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A alteração destes dados não será atualizada com o Mainframe. Os dados alterados serão visiveis somente no sistema GESIN..
        /// </summary>
        public static string AtualizacaoDadosContratoNaoSeraAtualizadaComMainframe {
            get {
                return ResourceManager.GetString("AtualizacaoDadosContratoNaoSeraAtualizadaComMainframe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aviso de Sinistro incluído com sucesso..
        /// </summary>
        public static string AvisoCriadoComSucesso {
            get {
                return ResourceManager.GetString("AvisoCriadoComSucesso", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A coluna [{0}] de nome &apos;{1}&apos; não foi encontrada no arquivo. Selecione outro arquivo para a importação..
        /// </summary>
        public static string ColunaNaoEncontrada {
            get {
                return ResourceManager.GetString("ColunaNaoEncontrada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPF precisa ser um número válido..
        /// </summary>
        public static string CpfInvalido {
            get {
                return ResourceManager.GetString("CpfInvalido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada uma conta com este CPF..
        /// </summary>
        public static string CpfNaoEncontrato {
            get {
                return ResourceManager.GetString("CpfNaoEncontrato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Os dados foram editados com sucesso..
        /// </summary>
        public static string DadosEditadosComSucesso {
            get {
                return ResourceManager.GetString("DadosEditadosComSucesso", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O valor de data {0} não foi configurado para MoedaEnum..
        /// </summary>
        public static string DataNaoConfiguradaParaMoedaEnum {
            get {
                return ResourceManager.GetString("DataNaoConfiguradaParaMoedaEnum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Você deve informar uma nova senha..
        /// </summary>
        public static string DeveInformarNovaSenha {
            get {
                return ResourceManager.GetString("DeveInformarNovaSenha", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erro na carga das tabelas para Cálculo do CES - OKCOTBA..
        /// </summary>
        public static string ErroCargaTabelasParaCalculoCesOkcotba {
            get {
                return ResourceManager.GetString("ErroCargaTabelasParaCalculoCesOkcotba", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erro não previsto pelo Mainframe..
        /// </summary>
        public static string ErroNaoPrevisto {
            get {
                return ResourceManager.GetString("ErroNaoPrevisto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erro no Cálculo do CES - CKCOAH..
        /// </summary>
        public static string ErroNoCalculoCesCkcoah {
            get {
                return ResourceManager.GetString("ErroNoCalculoCesCkcoah", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erro na obtenção das informações do Imóvel - OKCO1FA..
        /// </summary>
        public static string ErroObtencaoInformacoesDoImovelOkco1fa {
            get {
                return ResourceManager.GetString("ErroObtencaoInformacoesDoImovelOkco1fa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Esta funcionalidade não está disponível no momento..
        /// </summary>
        public static string EstaFuncionalidadeNaoEstaDisponivelNoMomento {
            get {
                return ResourceManager.GetString("EstaFuncionalidadeNaoEstaDisponivelNoMomento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Falha na autenticação do usuário..
        /// </summary>
        public static string FalhaAutenticacaoUsuario {
            get {
                return ResourceManager.GetString("FalhaAutenticacaoUsuario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FifConverter é valido somente para string..
        /// </summary>
        public static string FifConverterValidoSomenteParaString {
            get {
                return ResourceManager.GetString("FifConverterValidoSomenteParaString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Somente são aceitos os formatos de arquivo .xls e .xlsx..
        /// </summary>
        public static string FormatoExcelIncorreto {
            get {
                return ResourceManager.GetString("FormatoExcelIncorreto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O Mainframe reportou um erro..
        /// </summary>
        public static string MainframeReportouErro {
            get {
                return ResourceManager.GetString("MainframeReportouErro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não é possível criar um tipo {0} com um valor nulo..
        /// </summary>
        public static string NaoEPossivelCriarTipo0ComValorNulo {
            get {
                return ResourceManager.GetString("NaoEPossivelCriarTipo0ComValorNulo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não existe um estado civil para letra &apos;{0}&apos;..
        /// </summary>
        public static string NaoExisteEstadoCivilParaLetra {
            get {
                return ResourceManager.GetString("NaoExisteEstadoCivilParaLetra", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado uma ViewBag com o nome {0}..
        /// </summary>
        public static string NaoFoiEncontradoUmaViewbagComNomeDefinido {
            get {
                return ResourceManager.GetString("NaoFoiEncontradoUmaViewbagComNomeDefinido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não foi possível carregar informações do assembly da aplicação..
        /// </summary>
        public static string NaoFoiPossivelCarregarInfoAssembly {
            get {
                return ResourceManager.GetString("NaoFoiPossivelCarregarInfoAssembly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não foi possível conectar com o Mainframe.
        /// </summary>
        public static string NaoFoiPossivelConectarComMainframe {
            get {
                return ResourceManager.GetString("NaoFoiPossivelConectarComMainframe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não foi possível se conectar com o serviço de autenticação de usuário. Contacte um administrador do sistema..
        /// </summary>
        public static string NaoFoiPossivelConectarServidorAutenticacao {
            get {
                return ResourceManager.GetString("NaoFoiPossivelConectarServidorAutenticacao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O sinistro não tem uma Confirmação de Crédito cadastrado ainda, por isso não pode ser enviado para baixa de contrato no Mainframe..
        /// </summary>
        public static string NaoPodeEnviarBaixaContratoSemCreditoConfirmado {
            get {
                return ResourceManager.GetString("NaoPodeEnviarBaixaContratoSemCreditoConfirmado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Importação da Seguradora - Inconsistências.txt.
        /// </summary>
        public static string NomeArquivoImportacaoSeguradoraInconsistencias {
            get {
                return ResourceManager.GetString("NomeArquivoImportacaoSeguradoraInconsistencias", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O Número de Conta e CPF são divergentes..
        /// </summary>
        public static string NumeroContaECpfDivergentes {
            get {
                return ResourceManager.GetString("NumeroContaECpfDivergentes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O Número da Conta e CPF não podem ser nulos ou zero ao mesmo tempo..
        /// </summary>
        public static string NumeroContaECpfNulos {
            get {
                return ResourceManager.GetString("NumeroContaECpfNulos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada uma conta com este Número da Conta..
        /// </summary>
        public static string NumeroContaNaoEncontrato {
            get {
                return ResourceManager.GetString("NumeroContaNaoEncontrato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Número da Conta precisa ser um número válido..
        /// </summary>
        public static string NumeroDaContaInvalido {
            get {
                return ResourceManager.GetString("NumeroDaContaInvalido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Número de conta Inválido..
        /// </summary>
        public static string NumeroDeContaInvalido {
            get {
                return ResourceManager.GetString("NumeroDeContaInvalido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Número de CPF inválido..
        /// </summary>
        public static string NumeroDeCpfInvalido {
            get {
                return ResourceManager.GetString("NumeroDeCpfInvalido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O Binder {0} não suporta o tipo {1}..
        /// </summary>
        public static string OBinderNaoSuportaOTipo {
            get {
                return ResourceManager.GetString("OBinderNaoSuportaOTipo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar processar a informação desejada. Contacte um administrador do sistema..
        /// </summary>
        public static string OcorreuUmErroAoTentarProcessarAInformacao {
            get {
                return ResourceManager.GetString("OcorreuUmErroAoTentarProcessarAInformacao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O formato da letra da coluna esté incorreto..
        /// </summary>
        public static string OFormatoDaLetraDaColunaEstaIncorreto {
            get {
                return ResourceManager.GetString("OFormatoDaLetraDaColunaEstaIncorreto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O método GetDictionaryFromEnum é valido somente para enumerações baseadas em int..
        /// </summary>
        public static string OMetodoGetDictionaryFromEnumValidoSomenteParaEnumeracoesBaseadasEmInt {
            get {
                return ResourceManager.GetString("OMetodoGetDictionaryFromEnumValidoSomenteParaEnumeracoesBaseadasEmInt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A Operação é diferente de 1 ou 2..
        /// </summary>
        public static string OperacaoDiferenteDe1E2 {
            get {
                return ResourceManager.GetString("OperacaoDiferenteDe1E2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O ultimo termo de cobertura definido para o sinistro é TNC. TNC não podem ser enviados para baixa de contrato no Mainframe..
        /// </summary>
        public static string OTermoDeCoberturaNaoEValidoParaEnvioParaBaixa {
            get {
                return ResourceManager.GetString("OTermoDeCoberturaNaoEValidoParaEnvioParaBaixa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O tipo {0} não contém um valor válido para {1}..
        /// </summary>
        public static string OTipo0NaoContemValorValidoPara1 {
            get {
                return ResourceManager.GetString("OTipo0NaoContemValorValidoPara1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O tipo {0} não é válido para processamento de retorno do Mainframe..
        /// </summary>
        public static string OTipoNaoEValidoParaProcessamentoRetornoMainframe {
            get {
                return ResourceManager.GetString("OTipoNaoEValidoParaProcessamentoRetornoMainframe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O tipo {0} não herda de StringEnum por isso não pode ser convertido com o método Parse..
        /// </summary>
        public static string OTipoNaoHerdaDeStringEnumPorIssoNaoPodeSerConvertidoComMetodoParse {
            get {
                return ResourceManager.GetString("OTipoNaoHerdaDeStringEnumPorIssoNaoPodeSerConvertidoComMetodoParse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O valor {0} não é um tipo de sinistro válido..
        /// </summary>
        public static string OValorNaoEUmTipoDeSinistroValido {
            get {
                return ResourceManager.GetString("OValorNaoEUmTipoDeSinistroValido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registros TNC somente poderão ser inclusos na fase 4..
        /// </summary>
        public static string RegistrosTncSomentePoderaoSerInclusosNaFase4 {
            get {
                return ResourceManager.GetString("RegistrosTncSomentePoderaoSerInclusosNaFase4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sinistros do tipo DFI não podem ser enviados para baixa de contrato no Mainframe..
        /// </summary>
        public static string SinistrosDoTipoDFINaoPodemSerEnviadosParaBaixa {
            get {
                return ResourceManager.GetString("SinistrosDoTipoDFINaoPodemSerEnviadosParaBaixa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Somente são aceitos, para este processo, campos que comportam valor nulo..
        /// </summary>
        public static string SomenteSaoPermitidosCamposQueComportamNulo {
            get {
                return ResourceManager.GetString("SomenteSaoPermitidosCamposQueComportamNulo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O token passado está em um formato incorreto..
        /// </summary>
        public static string TokenEmFormatoIncorreto {
            get {
                return ResourceManager.GetString("TokenEmFormatoIncorreto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Um sinistro sem indenização cadastrada não pode ser enviado para baixa de contrato no Mainframe..
        /// </summary>
        public static string UmSinistroSemIndenizacaoCadastradaNaoPodeSerEnviadoParaBaixa {
            get {
                return ResourceManager.GetString("UmSinistroSemIndenizacaoCadastradaNaoPodeSerEnviadoParaBaixa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuário não existe..
        /// </summary>
        public static string UsuarioNaoExiste {
            get {
                return ResourceManager.GetString("UsuarioNaoExiste", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuário não possui permissão para acessar o sistema..
        /// </summary>
        public static string UsuarioNaoPossuiPermissao {
            get {
                return ResourceManager.GetString("UsuarioNaoPossuiPermissao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O usuario simulado não foi encontrado..
        /// </summary>
        public static string UsuarioSimuladoNaoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioSimuladoNaoEncontrado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O valor key não pode ser nulo.
        /// </summary>
        public static string ValorKeyNaoPodeSerNulo {
            get {
                return ResourceManager.GetString("ValorKeyNaoPodeSerNulo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O valor {0} não é aceito como objeto sinistrado válido..
        /// </summary>
        public static string ValorNaoAceitoComoObjetoSinistradoValido {
            get {
                return ResourceManager.GetString("ValorNaoAceitoComoObjetoSinistradoValido", resourceCulture);
            }
        }
    }
}
